name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  RunUnitTests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install pytest pytest-describe pytest-mock
      - name: Run Unit Tests
        run: pytest

  RunSystemTests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install pytest
        run: pip install pytest pytest-spec pytest-describe
      - name: Run pytest
        run: pytest --spec --color=yes test_battery.py

  RunFunctionalTests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install behave behave-webdriver selenium
      - name: Check chromedriver availability
        run: which chromedriver
      - name: Run Behave Tests
        run: |
          behave --no-capture --format pretty
        env:
          PATH: /usr/local/bin:$PATH